---
title: "Edits_to_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Creating variables for clean data
```{r}
library(readxl)
library(jsonlite)
akcData <- read.csv("akc-data-latest.csv")
westminsterData <- read_excel("Westminster_data_clean.xlsx")
dogOriginData <- fromJSON("dog-breeds.json")
```

Removing Owner column
```{r}
westminsterData = subset(westminsterData, select = -c(Owner, Winner))
```

Removing unneeded Columns from AKC Data
```{r}
akcData = subset(akcData, select = -c(description, popularity, grooming_frequency_value, grooming_frequency_category, shedding_value, shedding_category, energy_level_value, trainability_value, trainability_category, demeanor_value, energy_level_category, demeanor_category))
```

Removing unneeded Row from AKC Data
```{r}
akcData <- akcData[-c(237, 17, 56, 245), ]
```

Changing values in westminster Dataset to match origin. gsub() didn't help because often order was flipped
```{r}
westminsterData[westminsterData=="Fox Terrier (Smooth)"] <- "Fox Terrier, Smooth"
westminsterData[westminsterData=="Fox Terrier (Wire)"] <- "Fox Terrier, Wire"
westminsterData[westminsterData=="Beagle (15 Inch)"] <- "Beagle"
westminsterData[westminsterData=="Spaniel (Cocker) Black[B]"] <- "English Cocker Spaniel"
westminsterData[westminsterData=="Spaniel (Cocker) ASCOB[B]"] <- "English Cocker Spaniel"
westminsterData[westminsterData=="Spaniel (Irish Water)"] <- "Irish Water Spaniel"
westminsterData[westminsterData=="Bichon Frise"] <- "Bichon Frisé"
westminsterData[westminsterData=="Bull Terrier (White)"] <- "Bull Terrier"
westminsterData[westminsterData=="Collie (Rough)"] <- "Collie, Rough"
westminsterData[westminsterData=="Poodle (Toy)"] <- "Poodle"
westminsterData[westminsterData=="Spaniel (Cocker) Parti"] <- "English Cocker Spaniel"
westminsterData[westminsterData=="Spaniel (Clumber)"] <- "English Cocker Spaniel"
westminsterData[westminsterData=="Poodle (Standard)"] <- "Poodle"
westminsterData[westminsterData=="Poodle (Miniature)"] <- "Poodle"
westminsterData[westminsterData=="Bull Terrier (Colored)"] <- "Bull Terrier"
westminsterData[westminsterData=="German Shepard"] <- "German Shepard Dog"
westminsterData[westminsterData=="Pointer (German Shorthaired)"] <- "Pointer"
westminsterData[westminsterData=="Setter (English)"] <- "English Setter"
westminsterData[westminsterData=="Spaniel (English Springer)"] <- "English Springer Spaniel"
```


